### PR TITLE
Add first tests

### PR DESCRIPTION
**Pull request by statwonk**
@sckott this is a total stub. I added `connect(paste0("http://", Sys.getenv("ES_IP")))` to the main `testthat.R` file. How do you think we can best create a testing ES instance?

### CODE REVIEW

**Comment by sckott** [comment]
thanks. 

Take a look at how its setup for `elastic` https://github.com/ropensci/elastic/tree/master/tests 

here https://github.com/ropensci/elastic/blob/master/tests/test-all.R#L1-L8 we load some data and then all the tests https://github.com/ropensci/elastic/tree/master/tests/testthat are run based on that data that's loaded in. 

Those tests run well locally and on Travis-CI. See the travis file https://github.com/ropensci/elastic/blob/master/.travis.yml for how that's set up (key is that Elasticsearch is installed on started before R check is run)

**Comment by statwonk** [comment]
Oh excellent. I see how it's done. Very cool.

**Comment by sckott** [comment]
thanks, looks good, I'll make the addtn'l changes needed in the travis file

**Comment by statwonk** [comment]
:+1: thanks!

**Pull request merged**
