### PR TITLE
Add a simple way to list cluster indices.

### PR DESCRIPTION
**Pull request by statwonk**
I'm a huge fan of `elasticdsl` --- it's such a pain and inefficient to construct `elastic` queries by hand. This PR is as much me coming up to speed on the package as it is adding a feature. I was looking for a handy way to list all cluster indices, but didn't see an existing helper. Perhaps there's an idiom I'm missing? Guidance to that end for future contributions is appreciated.

### CODE REVIEW

**Comment by sckott** [comment]
thanks for the PR!  

> Perhaps there's an idiom I'm missing?

No, just hadn't thought about it yet

another way is `elastic::cat_indices(parse = TRUE)$V3` but the way you did it works nicely. 

Would you be up for changing the fxn name to simply `indices()` ?  It would line up with `index()` better i think.

**Comment by statwonk** [comment]
I use `elastic` in production at Zapier. Works great. I'm interested to help improve the package. I hope you won't mind a few questions seeking clarification in places.

**Comment by sckott** [comment]
> I use elastic in production at Zapier. Works great. 

great, let me know if there's any pain points you have 

> I'm interested to help improve the package. I hope you won't mind a few questions seeking clarification in places.

please do

I did ask above if you'd be up for changing the fxn name in this PR to simply `indices()`? Is that okay?

**Comment by statwonk** [comment]
I believe the commit above: https://github.com/statwonk/elasticdsl/commit/d51f2b35058703a16489a8223eef44ea85628c5e changes the name to `indices()`. Easy to miss, or am I missing something myself?

**Comment by sckott** [comment]
Woops! Sorry, I missed that. LGTM

**Pull request merged**
